Documentação do Treinamento de Scrum
fga-eps-mds/2021.1-Linguas-Indigenas-Docs pull request #15
Opened 2021-08-03 16:42 UTC by micaellagouveia

Closes #4 

- [x] Documentação treinamento scrum.

2021-08-03 17:32 UTC, sofiapatrocinio submitted a review, later dismissed

2021-08-03 21:12 UTC, GabrielDVpereira requested changes

2021-08-03 21:12 UTC, GabrielDVpereira commented on docs/Dojos/scrum.md
> +Para realização do treinamento sobre Scrum foi utillizado a seguinte apresentação.
utillizado -> utilizado

2021-08-04 18:23 UTC, sofiapatrocinio approved these changes

2021-08-04 20:32 UTC, merged