Adicionar Informações do Projeto no GitHub Pages
fga-eps-mds/2021.1-Linguas-Indigenas-Docs pull request #18
Opened 2021-08-03 20:00 UTC by sofiapatrocinio

## Descrição

Adição de informações do Projeto no GitHub Pages

## Solução

Adição dos slides e metodologias utilizadas no treinamento.

## Issue 
Resolve #17

## Tarefas
- [x]  Adicionar foto e nome dos membros
- [x] Adicionar breve descrição do projeto

## Assets
![Peek 2021-08-03 16-59](https://user-images.githubusercontent.com/38709421/128078314-91b1fa3f-c228-4465-9457-3993b472b3a8.gif)

2021-08-03 21:16 UTC, micaellagouveia submitted a review, later dismissed

2021-08-03 21:28 UTC, GabrielDVpereira requested changes

2021-08-03 21:28 UTC, GabrielDVpereira commented on docs/Project/methodology.md
> +*  **Product Backlog**: Um conjunto de funcionalidades pensadas e desejadas para o produto. Com o tempo, o Product Backlog cresce e muda à medida que se aprende mais sobre o produto e seus usuários .
remover o espaço entre o ponto final e a última palavra

2021-08-03 21:28 UTC, GabrielDVpereira commented on docs/Project/methodology.md
> +*  **Pair-Programming**: É eficaz para reduzir a incidência de bugs em um sistema e consiste em uma forma de trocar conhecimento, alinhar o grupo, tirar dúvidas e desenvolver algo em conjunto. É o mo
"axilie", seria "auxilie"?

2021-08-03 21:28 UTC, GabrielDVpereira commented on docs/Project/methodology.md
> +* **Collective Ownership**: Encorajamento de todos os membros a contribuírem em todos os seguimentos do projeto. Consiste em revezamento de pares, total autorizaçao para edição de código por qualquer
autorizaçao -> autorização

2021-08-03 21:28 UTC, GabrielDVpereira commented on docs/Project/methodology.md
> +*  **Code Reviews**: A revisão de código é feita pelos membros não participantes da issue entregue. A segunda parte é feita na reunião da Sprint onde o time avalia e repassa os conhecimento adquirido
os conhecimento adquiridos -> os conhecimentos adquiridos

2021-08-04 17:29 UTC, micaellagouveia approved these changes

2021-08-04 23:32 UTC, GabrielDVpereira approved these changes

2021-08-04 23:32 UTC, merged