Documentação Lean 3
fga-eps-mds/2021.1-Linguas-Indigenas-Docs pull request #37
Opened 2021-08-14 21:56 UTC by sofiapatrocinio

## Descrição
Adição da documentação relativa ao dia 3 da Lean Inception

## Solução
Documentação escrita no docsify para ser mostrada no GitHub Pages

## Issue 
Resolve #25

## Tarefas
- [x] Brainstorming de Funcionalidades
- [x ] Revisão Técnicas de Negócio
- [x] UX

## Assets
![Peek 2021-08-14 18-55](https://user-images.githubusercontent.com/38709421/129461058-459fa6bf-5571-43b3-b0e0-18536e3b7227.gif)

2021-08-15 14:11 UTC, GabrielDVpereira requested changes

2021-08-15 14:11 UTC, GabrielDVpereira commented on docs/LeanInception/dia3.md
> +Lean Inception é o nome dado ao workshop colaborativo para alinhar um grupo de pessoas sobre o produto mínimo viável a ser construído. Ele é feito durante uma semana, em quatro dias, contendo diversa
Acho no final desse parágrafo seria interessante falar sobre o dia 3 e não o dia 2

2021-08-15 14:11 UTC, GabrielDVpereira commented on docs/LeanInception/dia3.md
> +Classificamos cada funcionalidade combinando o nível de confiança técnico (como fazer) e o nível de confiança de UX e do negócio (o que fazer). Dessa maneira, cada funcionalidade recebeu uma cor rela
descartas -> descartadas

2021-08-16 00:50 UTC, pedroeagle requested changes

2021-08-16 00:50 UTC, pedroeagle commented on docs/_sidebar.md
> +    * [Dia 2](LeanInception/dia2.md)
Aqui deveria ser ```* [Dia 3](LeanInception/dia3.md) ```. Fui testar no docsify e tava dando 404

2021-08-16 01:47 UTC, micaellagouveia submitted a review, later dismissed

2021-08-16 02:06 UTC, micaellagouveia approved these changes

2021-08-16 02:09 UTC, pedroeagle approved these changes

2021-08-16 12:36 UTC, GabrielDVpereira approved these changes

2021-08-16 12:36 UTC, merged