Documentação do Lean 4
fga-eps-mds/2021.1-Linguas-Indigenas-Docs pull request #38
Opened 2021-08-16 02:08 UTC by pedroeagle

## Descrição
Adição da documentação relativa ao dia 4 da Lean Inception

## Solução
Documentação escrita no docsify para ser mostrada no GitHub Pages

## Issue 
Resolve #26 

## Tarefas
- [x]  Canvas MVP
- [x]  Sequenciador

## Assets

https://user-images.githubusercontent.com/45996980/129501809-cea45ef4-c558-4794-a8a4-bb2bad433340.mp4

2021-08-16 02:18 UTC, sofiapatrocinio requested changes

2021-08-16 02:18 UTC, sofiapatrocinio commented on docs/LeanInception/dia4.md
> +A partir dos mvps produzidos e suas respectivas funcionalides foi criado um sequenciador com o objetivo de listar funcionalidades que deveriam estar presentes nas primeiras versões da aplicação. A nu
Seria melhor colocar MVPs e "funcionalidades" ao invés de "funcionalides"

2021-08-16 02:18 UTC, sofiapatrocinio commented on docs/LeanInception/dia4.md
> +Helena, estudante de pós graduação em psicologia que viajará para uma região de comunidades indígenas.
O correto é "pós-graduação"

2021-08-16 12:35 UTC, GabrielDVpereira approved these changes

2021-08-16 16:39 UTC, micaellagouveia approved these changes
Só arrumar pedidos da Sofia e tá ok!

2021-08-16 22:33 UTC, GabrielDVpereira requested changes

2021-08-16 22:33 UTC, GabrielDVpereira commented on docs/LeanInception/dia4.md
> +Lean Inception é o nome dado ao workshop colaborativo para alinhar um grupo de pessoas sobre o produto mínimo viável a ser construído. Ele é feito durante uma semana, em quatro dias, contendo diversa
Acho que aq no fim do parágrafo seria interessante falar sobre o foco do 4 dia e não do segundo

2021-08-18 16:55 UTC, pedroeagle commented
Resolvido

2021-08-18 22:54 UTC, sofiapatrocinio approved these changes

2021-08-19 11:45 UTC, merged