Lean dia 1
fga-eps-mds/2021.1-Linguas-Indigenas-Docs pull request #40
Opened 2021-08-17 00:24 UTC by GabrielDVpereira

## Descrição
Documentação dos dados levantados pela dinâmica da Lean em seu primeiro dia. 

## Solução
Criação do documento e adição do mesmo no sidebar 

## Issue
Resolve #23

2021-08-17 03:07 UTC, micaellagouveia approved these changes

2021-08-17 15:10 UTC, sofiapatrocinio requested changes

2021-08-17 15:10 UTC, sofiapatrocinio commented on docs/LeanInception/dia1.md
> +Nessa primeira dinâmica, notou-se a perda de foco constante sobre a atividade. Isso gerou um atraso considerável que consumiu um tempo rasoável destinado ao primeiro dia. Devido a isso, foi gerado so
"Razoável" tá escrito errado

2021-08-17 15:10 UTC, sofiapatrocinio commented on docs/LeanInception/dia1.md
> +Uma das maneiras de entender um produto por diversas vezes é descrevendo o que ele não é ou não faz. Sendo assim, além de descrever as caracteriscas de um dado produto e seu comportamento, essa ativi
"Características" tá escrito errado

2021-08-17 15:10 UTC, sofiapatrocinio commented on docs/LeanInception/dia1.md
> +O após as dinâmicas anteriores, cada participante já possui algum entendimento do produto. Com isso, essa dinâmica consiste em cada um compartilhar o que entendeu ser os objetivos do mesmo. Em seguid
"O após as dinâmicas anteriores, cada participante já possui algum entendimento do produto." acho que essa frase ficou meio estranha

2021-08-19 02:08 UTC, sofiapatrocinio approved these changes

2021-08-19 02:10 UTC, merged