Dojo Node
fga-eps-mds/2021.1-Linguas-Indigenas-Docs pull request #41
Opened 2021-08-17 01:02 UTC by GabrielDVpereira

## Descrição
Documentação do treinamento de Node

## Solução
Criação do documento e adição do mesmo no sidebar 

## Issue
Resolve #27

2021-08-17 03:08 UTC, micaellagouveia approved these changes

2021-08-17 15:13 UTC, sofiapatrocinio approved these changes

2021-08-17 15:14 UTC, sofiapatrocinio requested changes
Tudo certo! Mas ao invés de adicionar o doc na sidebar, coloca no arquivo dojo.md

2021-08-19 02:09 UTC, sofiapatrocinio approved these changes

2021-08-19 02:10 UTC, merged