Dojo React Native
fga-eps-mds/2021.1-Linguas-Indigenas-Docs pull request #42
Opened 2021-08-18 15:06 UTC by GabrielDVpereira

## Descrição
Documentação do treinamento de React Native

## Solução
Criação do documento e adição do mesmo no arquivo de index

## Issue
Resolve #28

2021-08-18 16:45 UTC, micaellagouveia requested changes

2021-08-18 16:45 UTC, micaellagouveia commented on docs/Dojos/react.md
> +O React Native foi criado em 2015 pelo time de desenvolvimento do Facebook. Ele utiliza o conceito de desenvolvimento mobile híbrido, no qual o desenvolvedor tem a possibilidade de criar aplicações t
"Além do mais, o React Native trás com". Acho que pode ficar: **Além disso**, o React Native **traz** com...

2021-08-19 15:33 UTC, micaellagouveia approved these changes

2021-08-19 22:09 UTC, sofiapatrocinio approved these changes

2021-08-19 22:10 UTC, merged