Add context diagram
fga-eps-mds/2021.1-Linguas-Indigenas-Docs pull request #59
Opened 2021-08-29 01:30 UTC by pedroeagle

## Descrição
Adição do diagrama de contexto ao documento de arquitetura.

## Solução
Documentação escrita no docsify para ser mostrada no GitHub Pages

## Issue 
Resolve #50 

## Tarefas
- [x] Diagramas de contexto

2021-08-29 17:56 UTC, GabrielDVpereira approved these changes

2021-08-30 03:59 UTC, sofiapatrocinio approved these changes

2021-08-30 04:05 UTC, sofiapatrocinio requested changes

2021-08-30 04:05 UTC, sofiapatrocinio commented on docs/Project/docArquitetura.md
> +| 28/08/2021 | 1.2 | Adição do Diagrama de Contexto | Pedro Igor |
Pode adicionar a versão que mds fizeram na tabela?
| 28/08/2021 | 1.2 | Adição do Tópico 2 - Tecnologias | Grupo MDS |

2021-08-30 04:05 UTC, sofiapatrocinio commented on docs/Project/docArquitetura.md
Pode retirar o tópico de Diagramas de Casos de Uso? Esse diagrama não fará parte desse documento.

2021-08-30 11:41 UTC, merged